ci:
  autofix_commit_msg: "chore(pre-commit): autofix run"
  autofix_prs: false
  autoupdate_commit_msg: "chore(pre-commit): autoupdate hooks"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format
